language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "aleonmcdowell"
    token:
    secure: "E/A+01nmeL5GZhGn/9heQtoFdIWvQifvCwg3eLvjVlTGXPZmpBEG2RiDLMALi5BE6bDp2nks7SJWbxaG3+WV7z88bLp+am+0h+RXeELAMm9wG4olMSvsNTZ2o9/1v0+NHnDDii5zCJtOBb6KsbqihbX6mg6ipQf7I/bnECWfBiwRrof9+EvzRCu6auXXfRcGagFd1k6lRyVmk7iQxOjS9s+J/5x8Ac6zXSnBQy6KLvas2N6KHR5o+SZK0I0tfda10iQleNHXBlC697e0m4fJo91J4PNDtyCB6q6n5YR1GtQnWFSko9S0S9DHfPmYfLenLMvZ7o6G5slB/16U2F42M9UEMOUOOTr3UjwuSMb3lBBt50+7UmjDJvJPwxzAE7CeFNauL5RcniYXOzH5fO0TG5YFsNuVXx8yT19i3BBDWtMQ1qRRAKRtAI3cPtg/xiS4Hd3L/WppQP94PStVOHTM77fnvri22eVB5M7S/xRsyhrdRRn/h49ExB4MfK/CVPCePuPIsR7+TaZRDxMva3TnUeUfFA+DGvSw9xlxBxd9NTaQzTYsZoxo3xucSuRjJ5+r6VEPpQ6Sd6S4C6CFOCw6Id29UycHRnTISC665sA8u5ZSqwaLKssREpLb03zYgyPY8MMpMjFG2fTR9CtAo+FrGh5nlNxC0H39y6c+zgwv3+M="

jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
